### ISSUE TITLE
CSS Exercises 2 - Font Recommendations Don't Match Screenshot

### ISSUE THREAD

**Issue by curryworry** [TheOdinProject/css-exercises#10]
The screenshot in the README.md file (https://user-images.githubusercontent.com/70952936/131268858-5360bb32-27ba-4ce0-be59-5fda97f5eb12.png) shows all text as sans-serif (potentially Verdana).

The instructions state to only make the odd-numbered elements Verdana: "* **All odd numbered elements**: a light red/pink background, and a list of fonts containing `Verdana` as the first option and `sans-serif` as a fallback"

When the solutions HTML file is previewed, the even-numbered elements are indeed in a serif (default) font. 

This mismatch between screenshot, instructions, and the solution file might cause an issue to people working based on the screenshot file as they will think their output doesn't match the provided screenshot.

**Comment by Wanderer1980** [comment]
Thanks for posting this! I was curious about this discrepancy as well.

**Comment by codyloyd** [comment]
this is because the creator's computer defaults to that font instead of the serif font your computer is using.

might be worth updating... but we can't really predict what other users are going to see, and if we change it, it would be confusing for users that are getting sans-serif fonts in their local environment but seeing a serif font in the screenshot.

perhaps an easier solution overall would be to just specify a font so everyone sees the same thing lol.

**Comment by nerdee007** [comment]
This was confusing to me as well.  I think, in the future,  I'll just use the html solutions output to compare my output.  

I used monospace in this exercise to see if my solution was doing what it was supposed to be doing.

**Comment by thatblindgeye** [comment]
I feel the only way to ensure the screenshot matches what the user sees is by having the `style.css` file (outside of the solutions directory) include a font-family property. Doing so would defeat the purpose of the exercise, which is to have users practice writing out the syntax for adding a font-family to a selector on their own.

As the issue seems to have been resolved with an update to the README of the exercise providing a note about the potential visual mismatch in fonts between the screenshot and what the user sees, I will be closing this issue.
