### ISSUE TITLE
style.css Solutions for Margin and padding 2 issue

### ISSUE THREAD

**Issue by skeeler79** [TheOdinProject/css-exercises#111]
Hi-
The solution in for the style.css doc in the margin-and-padding-2 exercise eliminates the background color for the boxes.
<img width="506" alt="Screen Shot 2022-01-16 at 5 52 56 PM" src="https://user-images.githubusercontent.com/92762914/149681463-9cfc8fcc-8b15-453a-a571-c9078dfa9a72.png">

**Comment by thatblindgeye** [comment]
When I open the solution.html file, I see the background to the those three elements (the title, content, and button container), though they are difficult to see due to how light all the background colors are.

Are you sure you did not change anything in the solutions.css file, and that the screenshot you posted is from the provided solutions files and not your own solution?

**Comment by skeeler79** [comment]
Ok, then maybe I'm not understanding the solution completely. I had trouble
with this particular exercise, so I was studying the solution more closely
than the other exercises. Does the solution code, which is printed below
the original code, include only the changes that need to be made and not
the entire code?

When I was confused looking at the solution, I copy and pasted the code
into my VS code editor to see what the result would be. That is when I saw
that background colors disappear. But maybe the intent is that the solution
code is supposed to be added into the original given code and not the
complete code?

Below is the solution copied from the Odin Project GitHub just to help show
what I'm talking about.

Thanks for your help.
Sabrina
body {
background: #eee;
font-family: sans-serif;
}
.card {
width: 400px;
background: #fff;
margin: 16px auto;
}
.title {
background: #e3f4ff;
}
.content {
background: #e3f4ff;
}
.button-container {
background: #e3f4ff;
}
button {
background: white;
border: 1px solid #eee;
}
/* SOLUTION */
/* disclaimer: duplicating the selectors here isn't best practice.
In your solution you probably put it right inside the existing selectors,
which _is_ the best practice.
We separated it out here to make it extra clear what has changed. */
.card {
padding: 8px;
}
.title {
margin-top: 0;
margin-bottom: 8px;
font-size: 16px;
padding: 8px;
}
.content {
margin-bottom: 8px;
padding: 16px 8px;
}
.button-container {
text-align: center;
padding: 8px;
}
button {
display: block;
margin: 0 auto;
padding: 8px 24px;
}

   - <https://github.com/>© 2022 GitHub, Inc.


   - Terms
   <https://docs.github.com/en/github/site-policy/github-terms-of-service>
   - Privacy
   <https://docs.github.com/en/github/site-policy/github-privacy-statement>

**Comment by thatblindgeye** [comment]
Usually the content in the "Solutions" section of the code is just what should be added, unless otherwise stated (some exercise solutions may state "We removed XYZ...", for example).

So for this exercise, it looks like the code below the "Solution" area in the CSS file should be *in addition to* the original code, not in place of.

**Comment by thatblindgeye** [comment]
Closing as it seems the issue was more the instructions may not have been clear than an actual issue with the solution code.
