### ISSUE TITLE
Make a home landing page for all topics

### ISSUE THREAD

**Issue by bilalshaikh292** [TheOdinProject/css-exercises#387]
One single home page from where all the topic can be browsed.

**Comment by sahilbhise09** [comment]
I hope you're doing well. I came across the issue and i have started working on it can you assign it to me please

**Comment by bilalshaikh292** [comment]
hey @sahilbhise09 I am also a contributer and I am working on this issue . I created this issue as per the contribution guide

**Comment by bilalshaikh292** [comment]
I have done it and have created a PR also.

**Comment by ManonLef** [comment]
For big changes like this, please don't start work on it until a maintainer has reviewed and approved the change. An issue should also ideally utilise the template (feature request in this case) we provide to offer as much information as possible. 

could you please explain why you think this should be added? What the desired outcome is, what it adds for students following the curriculum and doing the exercises?

**Comment by bilalshaikh292** [comment]
![Uploading image.png…]()

**Comment by bilalshaikh292** [comment]
@ManonLef I have added this feature as the make the learning more easy. I have Made a single landing page where the user can browse all the content and start learning.

**Comment by ManonLef** [comment]
[this message from you with the image.png...](https://github.com/TheOdinProject/css-exercises/issues/387#issuecomment-1744601843) doesn't work for me. 

Maybe I fail to understand but the learners are instructed to fork and clone the repository and go through the exercises separately from there. Where would they see this landing page? Would it be inside the repository where they'd have to run it in the browser themselves? Or would it be part of the TOP website? I'd really like you to give me all the information you have and images would be great, since I'm a little lost here on the purpose and workings of your proposal 😅

**Comment by ManonLef** [comment]
thank you @pragyamishra56 but we will not be assigning this. We need more information on the intentions of the [change already made in a PR](https://github.com/TheOdinProject/css-exercises/pull/392)

**Comment by ManonLef** [comment]
I am closing this issue and the accompanying PR for I have received no response to the requests for more information. I have tried to come up with an appropriate use case, but I don't think we are looking to include something similar to this at the moment. 

If you still feel strongly about this being needed @bilalshaikh292 , please open an issue first being very clear of where this will reside, how it would be used, and why it would be an asset/improvement to what we currently have. As it looks now, our css-exercises have no homepage/webpage and I fail to see the need for it. It's best to not file a PR until we have approved of that issue, or have discussed it so we're on the same page. This is to avoid working on something that will not be included.

Thanks for your time anyway, we do appreciate the effort that went in.
