### ISSUE TITLE
Foundations Exercises: Remove Note On Accessibility For 06

### ISSUE THREAD

**Issue by jasonHYLam** [TheOdinProject/css-exercises#443]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `Foundations exercises: Add exercise for XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The following note: `Note: for accessibility reasons, the style in this exercise has changed. For new and old students, we propose to carry out the exercise noting how important it is to pay attention to the accessibility of the web, and we encourage more and more practices like this.`
Is currently at the bottom of the README of this exercise (06-cascade-fix). It creates unnecessary confusion for CSS beginners, and accessibility is currently being taught far, far later (in the Advanced HTML & CSS section). Thus the people completing this exercise would have no knowledge about accessibility and thus should not worry about this note.

I would like to propose removing this note to let learners focus on the exercise itself, instead of wondering what this note means when they have not encountered accessibility yet. 

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by thatblindgeye** [comment]
While I think letting users know about the concept of accessibility early on (even though we don't fully cover it until later) is helpful/useful, I agree with removing this note. It only really made sense at the time because there was discussion around the exercise in question, but we don't really need to let users know "hey, we updated this exercise from its original implementation for accessibility reasons". @jasonHYLam do you still want to work on this?

**Comment by jasonHYLam** [comment]
Hi @thatblindgeye, thanks for reviving this issue, I'd evidently forgotten to get round to it.
I can work on it. Is it fine to submit a PR even if it hasn't been approved?
