### ISSUE TITLE
flex/04-flex-information

### ISSUE THREAD

**Issue by VaultDweller13** [TheOdinProject/css-exercises#51]
It said twice in the self-check section that items should be arranged horizontally, not vertically. Yet in the solution there is `align-items: center` property in the .container class. Is that how it supposed to be? Third plant icon is visibly lover than others due to that.

**Comment by sriteja2602** [comment]
_items should be arranged horizontally, not vertically_  -  I think they mean that the div is not necessarily to be positioned vertically (using margin) and the align-items is used to align the flex items inside the display: flex div

**Comment by Munmun6392** [comment]
Hello @VaultDweller13  you can use framework to set items in center position.

**Comment by thatblindgeye** [comment]
As was mentioned in #96 I believe there is a simpler solution to this. For anyone that would like to be assigned, in order to resolve this issue please follow the below acceptance criteria:

* Remove the `align-items: center;` rule from the `.container` block in the solution.css file

This should fix the issue of the Self Check stating to not align things vertically, while also fixing the issue of one item looking lower than the rest (though this may not 100% alleviate that annoyance, as some images might have more white space along the top edge).

**Comment by scheals** [comment]
I created a PR and linked it to this issue. Sorry for not leaving a comment earlier.

**Comment by thatblindgeye** [comment]
Ah gotcha. Appreciate the enthusiasm! In the future just be sure to ask on an issue before starting any work; I doubt anyone else had been working on this issue but you never know.
