### ISSUE TITLE
Use actions to reduce unintentional PRs

### ISSUE THREAD

**Issue by fabulousgk** [TheOdinProject/css-exercises#527]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - Grid exercises: CSS not properly linked to HTML files`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

Before I spend a lot of time looking into how to do this...would the maintainers be open to an action that automatically closes any PR without a linked issue, in this and the other exercise repos.  The idea being that all the unitinended PRs are closed without effort from the maintainers, but still allowing legit PRs to stay open.

**Comment by MaoShizhong** [comment]
Thanks for making this suggestion @fabulousgk.
Had a little chat with some of the others and we're not we'd want to introduce this kind of action, even if we were to change the relevant repos' actions behaviours to run for first-time contributors.

While it might mean we no longer to manually close unwanted PRs, the proposed method would also catch any genuine PRs without linked issues. We don't actually *require* an issue, particularly for small fixes which are perfectly fine to directly PR without having to issue and wait for assignment. So there might be new issues that arise for us to deal with like handling mistakenly closed PRs or the like.

While that's not a *huge* issue, it's also not really that big of a deal to close these solution PRs since they don't come in all too often, and closing a few of them every now and then isn't too cumbersome of a task.

**Comment by thatblindgeye** [comment]
Going to close this as not planned, agreed with the above comments.
