### ISSUE TITLE
Mismatch between index.html and desired outcome in 03-grouping-selectors exercise

### ISSUE THREAD

**Issue by russelhanapi** [TheOdinProject/css-exercises#641]
The buttons in the HTML file do not reflect the outcome shown in the README.

## Screenshot
![Screenshot 2024-12-16 143243](https://github.com/user-attachments/assets/6d9ff954-5ed7-4afb-bcd0-b91bd9d0cc6d)

**Comment by CouchofTomato** [comment]
@TheOdinProject/html-css Can someone review please

**Comment by MaoShizhong** [comment]
I don't see any problems in the repo? The base HTML file has the button texts in the right order (and no classes yet since it's the one you work with), and the solution HTML also has them in the correct order with the appropriate classes that apply the styles as per the outcome image.

@russelhanapi your screenshot looks to be from the HTML file that you worked on - looks like you accidentally swapped the two buttons before you started adding classes? `(Alt+ up/down` moves lines up or down and is easy to hit by mistake)

**Comment by CouchofTomato** [comment]
Closing as it seems a local issue. Can reopen if required.
