### ISSUE TITLE
05-flex-modal: The solution is wrong

### ISSUE THREAD

**Issue by hmsiegel** [TheOdinProject/css-exercises#68]
The desired outcome image shows the close-button on the right hand side: 
![image](https://user-images.githubusercontent.com/49638789/142440041-fb737c16-cd37-44e8-b9b9-bd62fc55b2a0.png)

But, when pulling up the solution in my browser, this is what I get:
![image](https://user-images.githubusercontent.com/49638789/142440224-8a34ce85-69fd-42af-855e-80c0cd4d5f03.png)

Either the initial html code is incorrect, or the solution html code is incorrect. I have figured out the correct solution, but wasn't sure if I should open a pull request to fix it. Not sure if it should be fixed in the index.html or solution.html?

The correct code is:

```
<div class="header">Are you sure you want to do that?
        <div class="close-button">✖</div>
</div>
```

Instead of: 

```
<div class="header">Are you sure you want to do that?</div>
<div class="close-button">✖</div>
```

**Comment by thatblindgeye** [comment]
@hmsiegel  Per the README of this exercise:

"You'll need to edit the HTML a bit to get everything where it needs to be."

Therefore this is purposeful, as the user is meant to move the `close-button` `div` into the `header` `div`. Since there is nothing that needs updating in regards to this issue, I will be closing it. If you feel the instructions for the exercise could use improvement, please submit a new issue explaining any confusion, or you can submit a PR with a suggested change.

**Comment by hmsiegel** [comment]
@thatblindgeye I understand that the user is meant to move the` close-button` `div`. My comment was more geared towards the included solution, which isn't showing the `close-button` in the correct position.
